using UnityEngine;
using Amilious.Core.Extensions;

namespace Amilious.Core.Editor.Extensions {
    
    /// <summary>
    /// This class is used to add methods to the <see cref="GUIStyleState"/> class.
    /// </summary>
    public static class GUIStyleStateExtensions {
        
        /// <summary>
        /// This method is used to replace the background with a texture generated by the given color.
        /// </summary>
        /// <param name="state">The state that you want to set a background color for.</param>
        /// <param name="color">The color that you want to set the background to.</param>
        public static void SetBackGroundColor(this GUIStyleState state, Color color) {
            state.background = color.MakeTexture(2, 2);
        }

        /// <summary>
        /// This method is used to replace the background with a texture generated by the given color.
        /// </summary>
        /// <param name="state">The state that you want to set a background color for.</param>
        /// <param name="htmlCode">The color that you want to set the background to.</param>
        public static void SetBackgroundColor(this GUIStyleState state, string htmlCode) {
            if(!htmlCode.StartsWith("#")) htmlCode = $"#{htmlCode}";
            ColorUtility.TryParseHtmlString(htmlCode, out var color);
            state.SetBackGroundColor(color);
        }
        
    }
    
}